### ISSUE TITLE
Review entry criteria process

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#13]
**Background**
For Final Project, the Programme Managers used to identify with the Programme team who can be accepted/pass the [entry criteria](https://docs.google.com/document/d/18e84jL43b_xxLQCKROzIePDwq-gvxKcgZl7LTorPF3I/edit?tab=t.0#heading=h.8bipiccmzk3c). We need to define how this will work for Launch.

**Acceptance criteria**
- Understand how the previous process to review entry criteria was - talk to Sally (Programme) and Dara-Emma, Shaun or Halden (Programme Managers)
- Understand the differences of [Final Projects Entry criteria](https://docs.google.com/document/d/1jMxqI0L7IKFENCQ8Lw-D1lhnj3c3RZI_WK808wG4YJM/edit#heading=h.8bipiccmzk3c) and[ Launch Entry criteria](https://docs.google.com/document/d/18e84jL43b_xxLQCKROzIePDwq-gvxKcgZl7LTorPF3I/edit#heading=h.8bipiccmzk3c)
- Define the process and solution to review this
- Update the documentation to onboard/explain process
- Create other tickets if needed

**Comment by kfklein15** [comment]
I need some validation about how the old entry criteria process worked and how the new on could work. @SallyMcGrath , is this something you can validate? I'll happily reach out to the Programme Delivery team if needed, but was wondering if we both can tackle this :)

**Final Projects Entry process**
1. We checked the Trainee Tracker to identify if they the trainees was At or Beyond Milestones
2. Completed your mandatory coursework > _how did we check this?_
3. We checked Codility to see if they passed the Full Stack Assessment

**New process for Launch Module**
1. Completed all your mandatory coursework > _how can we check this? Or better, do we need to prioritise this for next sprint? Could this be added to the trainee tracker?_
3. Met your Milestones: trainee tracker
4. Applied to join the project with your CV, cover letter, and a portfolio: new form created - _could this go to the trainee tracker?_ 
5. Built, tested, deployed and demoed 2 Products using a stack you learned on the SDC, where at least 1 project is completed in a team > _how could we check this? could this be on the trainee tracker too?_
6. Passed the interview in which you demoed the Full Stack Product. It includes technical and competency-based questions. - we are working on this

**Comment by SallyMcGrath** [comment]
My main note here is instead of setting up us finding out all this information, move to requiring the trainee supply it. This is how we do the Fundamentals criteria, which works well (as you know!)

https://github.com/CodeYourFuture/Course-Fundamentals/issues/28

With this in mind, many of these questions answer themselves:

_Completed all your mandatory coursework > how can we check this?_ 

The trainee must assert they have done it  on the application form, and if it turns out they lied they have to leave. Their key work is tracked on the trainee tracker and their projects should be on their portfolios.  But there's no practical system where Tech Ed mentors review 92 pieces of coursework at the _end_ of the course instead of all the way _through_ the course as should be happening.

For other situations like this, we ask the trainee to assert and agree that they are happy to be examined. https://docs.google.com/forms/d/1RowlivKxurbGQlwJS3CilgH4Szez7C_sobdgDeTHu-0/edit

Trust but verify is a reasonable approach. Trainees are sometimes tempted to copypasta solutions into Codewars, for example, to get their ranking up, yet regular paired kata with Tech Ed volunteers exposes this IMMEDIATELY. I mean it is as obvious as someone pretending to speak French to a French person. You don't need an elaborate process, but Tech Ed must be prepared to ask simple technical questions and pair with trainees.  

Add a random coursework question into the interview process and write on the form that they will be asked at random from all the coursework they claim to have done. 

_Or better, do we need to prioritise this for next sprint? Could this be added to the trainee tracker?_

_Met your Milestones: trainee tracker
Applied to join the project with your CV, cover letter, and a portfolio: new form created - could this go to the trainee tracker?_

Do you want a selection tracker like https://docs.google.com/spreadsheets/d/1DKpi7czCGChOTwoyX3jjL9jJ32InNOlxjwwoa14coS0/edit?usp=sharing ?


_Built, tested, deployed and demoed 2 Products using a stack you learned on the SDC, where at least 1 project is completed in a team > how could we check this? could this be on the trainee tracker too?_ 

Their portfolio should contain these products. At this point their portfolio should contain at minimum TV Show Project (pair) and React Hotel (team) projects.  Put this all on a spreadsheet like the Fundamentals tracker and click the link, look at whether it meets the criteria, pass or fail the criterion.

_Passed the interview in which you demoed the Full Stack Product. It includes technical and competency-based questions. - we are working on this_

BTW, the volunteers reviewing https://github.com/CodeYourFuture/Full-Stack-Project-Assessment/pulls, which is the unlock/gate to apply to the Launch, can badge a project with a label eg Reviewed:Pass /  Reviewed: Fail . @Dedekind561 and @sztupy have been revising that super heavily and can speak more to this.

**Comment by SallyMcGrath** [comment]
I come back to say, it would be easy to build this form directly into the module

https://www.netlify.com/platform/core/forms/

And constrain applications to trainee email subdomains.

**Comment by kfklein15** [comment]
Thanks, @SallyMcGrath . I should have said that the form already does that: https://docs.google.com/forms/d/1Y6cgoDCZ6yB0vOUf5blHLKpgNnPuBEcta3zs_z_hMdE/edit :D But I thought we needed to check if they had done it. Is that not the case?

Full Stack Assessment is no longer part of the Entry criteria, just as "ending" the previous module. We replaced it with the 2 projects. Thanks for the names of the projects, so it's those 2 plus full stack assessment.

**Comment by kfklein15** [comment]
Forgot to reply about the PD Milestone question: I was wondering if it should just be in the trainee tracker itself, rather than a separate one.

**Comment by SallyMcGrath** [comment]
Can you let me know what the blocker is @kfklein15 ? I'm happy to help unblock but it's not clear to me what it is.

**Comment by kfklein15** [comment]
Thanks, @SallyMcGrath 

1. For the criteria evaluation: we are already asking the trainees to be the ones "formalising" that they have passed the criteria on our [form](https://docs.google.com/forms/d/1Y6cgoDCZ6yB0vOUf5blHLKpgNnPuBEcta3zs_z_hMdE/edit). Do we need to check these criteria or do we trust them 100% unless someone raises the opposite? 

2. PD Milestone: I will discuss this separately with you tomorrow in our planning.

**Comment by SallyMcGrath** [comment]
1. So I think we can trust by default but verify. This means randomly doing a 15 minute 1:1 pairing, like we do with Codewars. 

2. 👍

**Comment by SallyMcGrath** [comment]
Oh meant to say, it makes sense for you to have a separate tracker and import a final value into the main tracker. This is because the main tracker is already overcomplicated and people break it a lot by mistake - so let's not load on even more into it and just create a limited function tracker that can export the value we need. It can be imported directly into the performance view so from a volunteer perspective it's the same

**Comment by kfklein15** [comment]
1. So we need to organise Tech Ed volunteers to do this 1:1 15 min codewars for all applicants?
2. 
3. Makes sense.

**Comment by SallyMcGrath** [comment]
As part of the interview, my suggestion is that the applicant is asked to show/explain a random piece of coursework from the list they claim to have completed. Similar to how we ask them to walk through/refactor a random kata from the list they claim to have completed.

**Comment by kfklein15** [comment]
Step of reviewing a random CW or Kata has been added to the template.
