### ISSUE TITLE
CV Review standard

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#14]
**Background**
Trainees will send us their CVs, and we need to ensure that all volunteers review it with a standard lens.

**Acceptance criteria**
- Identify with the employability team (Barny) if we have a standard CV review document
- Review it to ensure it makes sense to Launch Module
- Make sure it is published somewhere easy to find
- Define the process of how we expect this to work (again, Barny can help with some input for this)
- Update the documentation to onboard/explain process

**Comment by girdenis-p** [comment]
[Discussion continued on Slack](https://codeyourfuture.slack.com/archives/CCTV4D93K/p1711542946111779?thread_ts=1711454962.183539&cid=CCTV4D93K)

**Comment by girdenis-p** [comment]
@kfklein15, @RC-PM can one of you take a look at the [current template for the standard](https://docs.google.com/document/d/1RFFKHllRhBEBSj1Yt4ZJq_RFq-bmQS5b143g29CY9UU/edit?usp=sharing)? As mentioned in the document, this standard is based off [the one in the portfolio module](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv). I tweaked it so that it specifies how the applicants should be expected to tailor their CV to the role.

I have a couple of questions I need some clarification on.
1) In the original CV criteria it suggested using Resumeworded. I imagine this would be good for simulating an applicant tracking system but, to my current knowledge, its free trial is limited so I'm not sure we could expect volunteers to use it to help evaluate the CV. Do we need this step?
2) I have also took out the "Include at least 2/3 experiences outside of CYF" criteria since I wasn't sure applicants would be able to reasonably do this. Is it okay to remove this step as well?

Feel free to give any general feedback on this too.

**Comment by kfklein15** [comment]
Thanks, @girdenis-p 
1. Resumeworded: we can leave it for now. Barny is looking into a substitute of this.
2. We can say: if possible or if you have, add 2-3 experiences in it.

We need to agree on 1 version, so are you suggesting substituting Barny's criteria with ours? If yes, has he approved it?

**Comment by girdenis-p** [comment]
> Thanks, [@girdenis-p](https://github.com/girdenis-p)
> 
>     1. Resumeworded: we can leave it for now. Barny is looking into a substitute of this.
> 
>     2. We can say: if possible or if you have, add 2-3 experiences in it.
> 
> 
> We need to agree on 1 version, so are you suggesting substituting Barny's criteria with ours? If yes, has he approved it?

I am not suggesting that, I'm saying that we should we should use Barny's criteria as a base. However, Barny has mentioned that his criteria doesn't explain how a CV should align to a job spec in detail, so I think we should elaborate in the standard how one is expected to tailor their CV to the role they apply for in the Launch.

**Comment by kfklein15** [comment]
Thanks, @girdenis-p . Can we make 1 version that is valid for ANY CYF Cv? We can amend the content on Barny's one easily - and I can publish it on the new curriculum.

I don't want a different standard for Launch. Applying to a job and sending a CV is the same process for every company, so let's get 1 standard in. Sorry if this wasn't clear on my original description.

**Comment by girdenis-p** [comment]
Yeah I understand and I agree with the want for one standard. Although, I'm a little confused about how to approach this because the standard on the Portfolio Module seems to be a guideline for trainees to follow when making their CV, while we are making a standard for volunteers to follow when reviewing CVs. The subtle difference is that some things are more reasonable to ask for of trainees than volunteers. E.g. a trainee is unlikely to use up their free trial of Resumeworded as fast as a volunteer reviewing CVs would.

I propose that we aim to update the standard on the Portfolio Module but also make a document detailing what we don't expect volunteers to do when reviewing the CVs. E.g. don't use Resumeworded and don't expect experience outside of CYF.

**Comment by kfklein15** [comment]
I like the idea of just highlighting what volunteers shouldn't check. This would make it simple and easy, since the build of it and the check of it is the same, except for these.

**Comment by girdenis-p** [comment]
@kfklein15, as we discussed, we need to transfer the points from [the standard](https://docs.google.com/document/d/1RFFKHllRhBEBSj1Yt4ZJq_RFq-bmQS5b143g29CY9UU/edit) to [the portfolio module](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv) GitBook for clarity. After you do that, let me know and I can update the standard again to tell the volunteers what not to do. Then we should be all done with this ticket.

**Comment by kfklein15** [comment]
[This has been updated on Portfolio Module](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv). Am checking how to add this directly to the Guides on the Curriculum (but that's a different scope)
