### ISSUE TITLE
Full Stack Project Assessment: check if it should be archived

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#18]
**Background**
For Final Projects we used the [Full Stack Project Assessment](https://github.com/CodeYourFuture/Full-Stack-Project-Assessment/blob/main/300.md) to identify if the trainees were ready

**Acceptance criteria**
- Check with Tech Ed if this exercise should be archived
- Make sure the exercise isn't on the Curriculum

**Comment by kfklein15** [comment]
@Dedekind561 , have you managed to look into this ticket by any chance?

**Comment by Dedekind561** [comment]
Apologies I've not updated this issue with my current progress on this - I was in the middle of checking the [new Full Stack Project Assessment](https://github.com/CodeYourFuture/Full-Stack-Project-Assessment/pull/454) that Zsolt has re-written and have ended up neglecting this issue. 

> @Dedekind561 , I need your help with following questions:
> 
> 1. On the [entry criteria](https://docs.google.com/document/d/18e84jL43b_xxLQCKROzIePDwq-gvxKcgZl7LTorPF3I/edit?tab=t.0#heading=h.8bipiccmzk3c) we said people must have "Built, deployed and demoed 2 Products, including tests, using a stack you learned on the SDC, where at least 1 project is completed in a team". Can you confirm if we have 2 products during the SDC course that have these rules?

Almost yes. Before the databases module, they'll have done the [TV Show Project](https://github.com/CodeYourFuture/JS3-Module-Project) and the [React Hotel Project](https://github.com/CodeYourFuture/React-Module-Project).  They are expected to do the React Hotel Project in teams. The reason why this is an _almost_ yes is because we don't state that trainees must write tests for the TV Show project. I suggest changing the phrasing of the rule in the entry requirements doc to be less strict, see below:

> 2. If we do NOT have 2 SDC project, do we change the rule or do we make people work on products BEFORE they are even allowed to apply to Launch?
- Given my response to 1. I think there should only be a subtle change to the rule you specified earlier:

> "Built, _tested_, deployed and demoed 2 Products, using a stack you learned on the SDC, where at least 1 project is completed in a team".

I think it should be phrased like this at the moment because "testing" here could just mean manual testing and not automated testing. Even though the dream would be for them to devise their own automated tests (and in Hotel Project they are asked to do this) I still think it's too early to expect trainees to start doing this themselves during JS3 when they're doing the TV show project. Except for the most able trainees.

> 3. Do we need to archive the [Full Stack Project assessment?](https://github.com/CodeYourFuture/Full-Stack-Project-Assessment). Or clarify that it is no longer used on the ReadMe?

I don't think we need to archive it at this point. This project is still being used in `Module-Databases`, see here: https://curriculum.codeyourfuture.io/databases/sprints/1/backlog/. I was going to check Zsolt's PR first before replying to this point: however, from what I can see I think the Full Stack Project has been improved significantly. I'm hoping it will be a much better preparation for the Launch module. There is a much greater focus on deployment and thinking in terms of features.

## Summary

Sorry there was a lot there!

For the upcoming cohorts WM5 and NW6:
- don't archive Full Stack Project Assessment
- change the rule on the Entry criteria for Launch to be less strict re tests
- after NW6, check to see if the Full Stack Project Assessment Project has been useful in preparing trainees for the Launch

Of course, I might be missing some context here and you might be opposed to the Full Stack Project for reasons I've missed. Happy to discuss this further if you have some different expectations re the future of the project.

**Comment by kfklein15** [comment]
Thanks, Mitch, super thorough and clear, as usual. Changes accepted on the file :)
