### ISSUE TITLE
Interview Feedback Standard and process

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#19]
**Background**
We want every trainee to be given a feedback of their interview, CV, Portfolio and Cover Letter

**Acceptance criteria**
- Would you hire this person? If not, explain why
- Check if we have a standard way of giving feedback
- If not, define one
- Document it with examples
- Add it to the onboarding/process documentation

**Comment by girdenis-p** [comment]
I have opted to make a [standard using the IDEA feedback model](https://docs.google.com/document/d/1VQA9hM057DSVgWFXL2VEqM8alAXuRwQ7FNfx9eZPE2k/edit) and I have added a single example so far. Can you please check if this is the type of standard we are wanting to use?

**Comment by girdenis-p** [comment]
Additionally, any partially completed examples would be helpful i.e. just the question, candidate response, and the identify step, potentially highlighting any common mistakes you have seen in interviews so that the examples are more relevant. I would be willing to complete any examples given.

**Comment by kfklein15** [comment]
@girdenis-p , examples that I can give:
- technical: during the demo of your product, not being able to explain why you used post API instead of put (or something along those lines) :D 
- technical: not being able to explain a Kata done by them and why/how you did that specific solution
- positive feedback: asking about needing someone's help and giving a clear example of team work, how you asked the question, the reply you got, how you solved the problem and how you learned from it/what you did from then on. (basically using STAR answers the correct way)

**Comment by girdenis-p** [comment]
@kfklein15 I have [updated the document](https://docs.google.com/document/d/1VQA9hM057DSVgWFXL2VEqM8alAXuRwQ7FNfx9eZPE2k/edit). I realised we wanted to focus more on giving feedback as a whole than feedback to each individual question so I have added some examples to show how you can create potential feedback from each questions, and then I gave the whole feedback showing the combination of different points raised when breaking down the questions into feedback. Let me know if you would prefer the current method in the document, or an alternative e.g. such as applying the IDEA model to the entire interview given instead of to individual questions.

As always any comments are appreciated.

**Comment by kfklein15** [comment]
They look good to me :) Let's ask some of the volunteers for feedback when we get them going.
