### ISSUE TITLE
Trainee Exit review documentation

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#25]
**Background**
We have a [current template ](https://docs.google.com/document/d/1sgNNJNsgWprh7VMCbiRgXY1BrqjzqxdWKKxSvTZwcjk/edit)to have a review of the trainees at the end of the Module

**Acceptance criteria**
- Decide if we want to use the same template
- If not, create a new template and validate it with the Programme Team
- Define who should be responsible for writing this review
- Define who should be responsible for approving the review
- Define who should be responsible for sending the reviews out
- Document this process

**Comment by girdenis-p** [comment]
I think this documentation is fine. Since we need to write about both the soft skills and tech skills of the trainees, I would suggest that the volunteer tech leads write this and the soft skills get reviewed by the product managers. The product managers could also review the tech skills if they feel confident doing so (otherwise I'm not sure who would review that).

What do you suggest @kfklein15 @RC-PM?

**Comment by kfklein15** [comment]
Although they have different expertise, I think both lead roles should agree on what they will write about the trainee. One can write and review it with the other, but I should be able to ask either of them about the given feedback (without too much technical detail).
